[project]
name = "ttt-diffusion-adaptation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "image-reward",
    "accelerate>=0.16.0",
    "datasets>=2.11.0",
    "diffusers>=0.16.0",
    "fairscale>=0.4.13",
    "ipykernel>=7.1.0",
    "pip>=25.3",
    "timm>=0.6.13",
    "torch>=2.9.1",
    "transformers>=4.27.4",
    "hf>=1.1.0",
    "protobuf>=6.33.1",
    "safetensors>=0.6.2",
    "sentencepiece>=0.2.1",
]

[tool.uv.sources]
# Only keep the local path dependency for image-reward
"image-reward" = { path = "./libs/ImageReward", editable = true }
